# Generated by Django 3.2.3 on 2021-05-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
                ('late_penalty', models.TextField(max_length=200)),
                ('absent_penalty', models.TextField(max_length=200)),
                ('period', models.TextField(max_length=200)),
                ('late_criterion', models.TextField(max_length=200)),
                ('absent_criterion', models.TextField(max_length=200)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=30)),
                ('max_member', models.IntegerField()),
                ('num_member', models.IntegerField()),
                ('mission_day', models.DateField(blank=True, default=None, null=True)),
                ('mission_time', models.TimeField(blank=True, default=None, null=True)),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app_study.studycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='app_study.study')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app_study.study')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='app_study.study')),
            ],
        ),
    ]
