# Generated by Django 3.2.3 on 2021-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0002_auto_20210529_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='StudyCategory',
        ),
    ]
