# Generated by Django 3.2.3 on 2021-05-29 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_study', '0004_auto_20210530_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='app_study.study'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joins', to=settings.AUTH_USER_MODEL),
        ),
    ]
