# Generated by Django 3.2.3 on 2021-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='record',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
