# Generated by Django 3.2.3 on 2021-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='술 이름')),
                ('taste', models.CharField(max_length=200, verbose_name='맛')),
                ('alcohollevel', models.IntegerField(blank=True, null=True, verbose_name='도수')),
                ('sweetlevel', models.IntegerField(blank=True, null=True, verbose_name='당도')),
                ('old', models.TextField(blank=True, null=True, verbose_name='one line description')),
                ('info', models.TextField(verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placetitle', models.CharField(max_length=200, verbose_name='가게 이름')),
                ('address', models.TextField(verbose_name='주소')),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='네이버 평점')),
                ('info', models.TextField(verbose_name='설명')),
                ('cocktail', models.IntegerField(verbose_name='칵테일fk')),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
