# Generated by Django 3.2.3 on 2021-05-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockdailyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.IntegerField(blank=True, verbose_name='네이버 평점'),
        ),
    ]
