# Generated by Django 3.2.3 on 2021-05-29 22:07

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작시간')),
                ('end_time', models.DateTimeField(verbose_name='마감시간')),
                ('title', models.CharField(max_length=50, verbose_name='이벤트 이름')),
                ('description', models.TextField(verbose_name='상세')),
            ],
            options={
                'verbose_name': '이벤트 데이터',
                'verbose_name_plural': '이벤트 데이터',
            },
        ),
        migrations.CreateModel(
            name='Fotd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='', max_length=300)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Totd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='', max_length=300)),
                ('color', colorfield.fields.ColorField(choices=[('#FDFBC7', '1'), ('#ECC5C7', '2'), ('#E29EAF', '3'), ('#A38FAB', '4'), ('#918DAB', '5'), ('#79849F', '6')], default='#FFFFFF', max_length=18)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('introduction', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ootd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='', max_length=300)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('moods', models.CharField(choices=[('1', '행벅'), ('2', '꿀꿀'), ('3', '짜증'), ('4', '우울'), ('5', '평온'), ('6', '나도 날 몰라')], max_length=50)),
                ('content', models.TextField(default='', max_length=1000)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Ootd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ootd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_ootd', to='oftoday.ootd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_ootd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Fotd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_fotd', to='oftoday.fotd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_fotd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
