# Generated by Django 3.2.3 on 2021-05-29 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_ID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LikeStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=30)),
                ('image', models.TextField(default=None, null=True)),
                ('point', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='app_registration.department')),
                ('likeGift', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeGift', to='app_registration.giftcategory')),
                ('likeStudy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeStudy', to='app_registration.likestudy')),
                ('myGift', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myGift', to='app_registration.giftcategory')),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='app_registration.university')),
                ('username', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
