# Generated by Django 3.2.3 on 2021-05-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likeGift',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='myGift',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='point',
        ),
    ]
