# Generated by Django 3.2.3 on 2021-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registration', '0002_auto_20210529_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCategory',
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likeStudy',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='LikeStudy',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
